<?php /* GENERATED by tools/extract.php from home-preview.html. Edit the source file and re-run; changes here are overwritten. */ ?>
<div class="ig-home">

  <!-- ==========================================================
       1. HERO SLIDER
       ========================================================== -->
  <section class="ig-hero" id="igHero" aria-roledescription="carousel" aria-label="Featured offers">

    <div class="ig-hero__track">

      <!-- EDIT: pricing and terms -->
      <div class="ig-hero__slide ig-hero__slide--braces is-active"
           role="group" aria-roledescription="slide" aria-label="1 of 2">

        <div class="ig-hero__media">
          <img src="/assets/img/home-page-hero-image-kids-ortho.jpg" alt="Smiling girl wearing braces" width="1920" height="1080" fetchpriority="high" decoding="async">
        </div>

        <div class="ig-wrap">
          <div class="ig-hero__inner">
            <div class="ig-hero__copy">

              <div class="ig-hero__badge">
                <span class="ig-hero__badge-top">Braces from</span>
                <span class="ig-hero__badge-mid">$99<sup>*</sup></span>
                <span class="ig-hero__badge-bot">per month</span>
              </div>

              <h2 class="ig-hero__head">A Straight Smile That Fits Your <b>Budget.</b></h2>
              <p class="ig-hero__terms">*Offer terms and eligibility apply.</p>

              <div class="ig-btns">
                <a class="ig-btn ig-btn--primary" href="<?= e(booking_url()) ?>">Schedule Now</a>
                <a class="ig-btn ig-btn--white" href="tel:<?= e(cfg('phone_tel')) ?>">Call Now</a>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="ig-hero__slide ig-hero__slide--aligners"
           role="group" aria-roledescription="slide" aria-label="2 of 2">

        <div class="ig-hero__media">
          <img src="/assets/img/home-page-hero-image-adults-orth.jpg" alt="Woman holding a clear aligner" width="1920" height="1080" loading="lazy" decoding="async">
        </div>

        <div class="ig-wrap">
          <div class="ig-hero__inner">
            <div class="ig-hero__copy">

              <div class="ig-hero__badge">
                <span class="ig-hero__badge-top">Clear Aligners from</span>
                <span class="ig-hero__badge-mid">$185<sup>*</sup></span>
                <span class="ig-hero__badge-bot">per month</span>
              </div>

              <h2 class="ig-hero__head">Wear Your <b>Best Smile.</b></h2>
              <p class="ig-hero__terms">*Offer terms and eligibility apply.</p>

              <div class="ig-btns">
                <a class="ig-btn ig-btn--primary" href="<?= e(booking_url()) ?>">Schedule Now</a>
                <a class="ig-btn ig-btn--white" href="tel:<?= e(cfg('phone_tel')) ?>">Call Now</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <button class="ig-hero__nav ig-hero__nav--prev" type="button" aria-label="Previous slide">
      <svg width="22" height="22" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M15.4 4.6 13.9 3.1 5 12l8.9 8.9 1.5-1.5L8 12z"/></svg>
    </button>
    <button class="ig-hero__nav ig-hero__nav--next" type="button" aria-label="Next slide">
      <svg width="22" height="22" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M8.6 4.6 10.1 3.1 19 12l-8.9 8.9-1.5-1.5L16 12z"/></svg>
    </button>

    <div class="ig-hero__dots" role="tablist" aria-label="Choose slide">
      <button type="button" class="is-active" aria-label="Slide 1"></button>
      <button type="button" aria-label="Slide 2"></button>
    </div>
  </section>


  <!-- ==========================================================
       2. TREATMENTS
       ========================================================== -->
  <section class="ig-sec ig-treat">
    <div class="ig-wrap">

      <div class="ig-treat__head">
        <span class="ig-kicker">Orthodontic Treatment Options</span>
        <h1>A Smile Is <em>Timeless.</em> Your Treatment Should Fit You.</h1>
        <p class="ig-treat__lead">There isn&rsquo;t one right way to straighten every smile. Ignite Orthodontics offers proven treatment options for children, teens, and adults, so you can find an approach that fits your orthodontic needs, preferences, and lifestyle.</p>
      </div>

      <!-- EDIT: point each card at its treatment page -->
      <div class="ig-treat__grid">

        <a class="ig-card-t" href="/types-of-braces/traditional-braces/">
          <img src="/assets/img/IMG_20260814_125055.jpg" alt="Teenager smiling with traditional metal braces" width="800" height="800" loading="lazy" decoding="async">
          <div class="ig-card-t__body">
            <h3 class="ig-card-t__title">Traditional <br>Metal Braces</h3>
            <p class="ig-card-t__desc">A proven approach to straightening teeth and correcting a wide range of orthodontic concerns.</p>
            <span class="ig-card-t__more">Learn More <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M8.6 4.6 10.1 3.1 19 12l-8.9 8.9-1.5-1.5L16 12z"/></svg></span>
          </div>
        </a>

        <a class="ig-card-t" href="/gold-braces/">
          <img src="/assets/img/IMG_20260814_125131.jpg" alt="Close-up of gold braces on upper and lower teeth" width="800" height="800" loading="lazy" decoding="async">
          <div class="ig-card-t__body">
            <h3 class="ig-card-t__title">Gold <br>Braces</h3>
            <p class="ig-card-t__desc">The reliability of traditional braces with a polished gold finish for patients who want their treatment to stand out.</p>
            <span class="ig-card-t__more">Learn More <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M8.6 4.6 10.1 3.1 19 12l-8.9 8.9-1.5-1.5L16 12z"/></svg></span>
          </div>
        </a>

        <a class="ig-card-t" href="/clear-aligners/">
          <img src="/assets/img/IMG_20260814_125204.jpg" alt="Patient placing a clear aligner tray" width="800" height="800" loading="lazy" decoding="async">
          <div class="ig-card-t__body">
            <h3 class="ig-card-t__title">Clear <br>Aligners</h3>
            <p class="ig-card-t__desc">Removable, discreet trays that gradually straighten your teeth without traditional brackets and wires.</p>
            <span class="ig-card-t__more">Learn More <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M8.6 4.6 10.1 3.1 19 12l-8.9 8.9-1.5-1.5L16 12z"/></svg></span>
          </div>
        </a>

        <a class="ig-card-t" href="/types-of-braces/ceramic-braces/">
          <img src="/assets/img/IMG_20260814_125146.jpg" alt="Close-up smile with tooth-coloured ceramic braces" width="800" height="800" loading="lazy" decoding="async">
          <div class="ig-card-t__body">
            <h3 class="ig-card-t__title">Ceramic <br>Braces</h3>
            <p class="ig-card-t__desc">Tooth-colored brackets offer effective orthodontic treatment with a more subtle appearance.</p>
            <span class="ig-card-t__more">Learn More <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M8.6 4.6 10.1 3.1 19 12l-8.9 8.9-1.5-1.5L16 12z"/></svg></span>
          </div>
        </a>

      </div>

      <div class="ig-treat__cta">
        <a class="ig-btn ig-btn--primary" href="<?= e(booking_url()) ?>">Schedule a Consultation</a>
      </div>
    </div>
  </section>


  <!-- ==========================================================
       3. BOOK A NO-COST CONSULTATION
       ========================================================== -->
  <?php require APP . '/views/partials/consult-cta.php'; ?>


  <!-- ==========================================================
       4. IGNITE ORTHODONTICS' PROMISE
       ========================================================== -->
  <section class="ig-sec">
    <div class="ig-wrap">

      <div class="ig-promise__head">
        <span class="ig-kicker">The Ignite Difference</span>
        <h2>Orthodontic Care <em>Built Around You.</em></h2>
        <p>Choosing an orthodontist is about more than finding someone who can straighten teeth. It&rsquo;s about finding a team that listens, explains your options clearly, and makes treatment work with your life.</p>
        <p style="margin-top:1.1em;">At Ignite Orthodontics, we combine specialist orthodontic care with flexible options designed around our patients. From your first consultation through the final stages of treatment, our goal is to make your experience clear, comfortable, and easier to manage.</p>
      </div>

      <div class="ig-promise__grid">

        <div class="ig-card-p">
          <div class="ig-card-p__icon">
            <!-- clock inside a refresh loop -->
            <svg viewBox="0 0 64 64" aria-hidden="true">
              <circle cx="32" cy="32" r="14"/>
              <path d="M32 24v8.6l6 3.4"/>
              <path d="M53.5 22.5A24 24 0 0 0 9.4 27"/>
              <path d="M44.5 21.6l9.6 1.6 1.6-9.6"/>
              <path d="M10.5 41.5A24 24 0 0 0 54.6 37"/>
              <path d="M19.5 42.4l-9.6-1.6-1.6 9.6"/>
            </svg>
          </div>
          <h4>Night &amp; Weekend Appointments</h4>
          <p>Your schedule doesn&rsquo;t always fit a traditional 9-to-5. We offer convenient appointment times to make orthodontic care easier to fit around work, school, and family.</p>
        </div>

        <div class="ig-card-p">
          <div class="ig-card-p__icon">
            <!-- payment card with a coin -->
            <svg viewBox="0 0 64 64" aria-hidden="true">
              <rect x="6" y="15" width="44" height="30" rx="4"/>
              <path d="M6 25h44"/>
              <path d="M14 36h9"/>
              <circle cx="46" cy="42" r="12"/>
              <path d="M46 36.5v11M43 39h4a2.5 2.5 0 0 1 0 5h-2a2.5 2.5 0 0 0 0 5h4"/>
            </svg>
          </div>
          <h4>Flexible Payment Options</h4>
          <p>Orthodontic treatment is an investment. Flexible payment options can help you spread the cost of care and choose an approach that works with your budget.</p>
        </div>

        <div class="ig-card-p">
          <div class="ig-card-p__icon">
            <!-- policy document with a verified shield -->
            <svg viewBox="0 0 64 64" aria-hidden="true">
              <path d="M12 8h22l12 12v18"/>
              <path d="M12 8v48h20"/>
              <path d="M34 8v12h12"/>
              <path d="M20 28h18M20 36h18M20 44h10"/>
              <path d="M46 34l11 4.6v7.4c0 6.4-4.7 11.6-11 13-6.3-1.4-11-6.6-11-13v-7.4z"/>
              <path d="M41 44.5l3.6 3.6 6.4-7"/>
            </svg>
          </div>
          <h4>Insurance-Friendly Care</h4>
          <p>We work with many dental insurance plans and can help you understand your available orthodontic benefits and expected out-of-pocket costs.</p>
        </div>

      </div>
    </div>
  </section>


  <!-- ==========================================================
       5. INSURANCES WE ACCEPT
       ========================================================== -->
  <section class="ig-sec ig-ins">
    <div class="ig-wrap">
      <div class="ig-ins__head">
        <span class="ig-kicker">Insurance &amp; Payment Options</span>
        <h2>Make the Most of Your <em>Dental Benefits.</em></h2>
        <p>Paying for orthodontic treatment shouldn&rsquo;t leave you guessing about what your insurance will cover. Ignite Orthodontics works with many major insurance plans and can help you understand your benefits before treatment begins.</p>
        <p style="margin-top:1.1em;">We&rsquo;ll help you look at your coverage, explain what it means for your treatment, and identify payment options for any remaining costs.</p>
        <div class="ig-ins__cta"><a class="ig-btn ig-btn--primary" href="<?= e(booking_url()) ?>">Schedule a Consultation</a></div>
        <p class="ig-ins__label">Accepted Insurance</p>
      </div>
    </div>

    <!-- the track is duplicated by JS so the leftward scroll loops seamlessly -->
    <div class="ig-marquee">
      <div class="ig-marquee__track" id="igMarquee">
        <div class="ig-ins__logo"><img src="/assets/img/insurences-4.webp" alt="BlueCross BlueShield of Illinois and Cigna" width="200" height="220" loading="lazy" decoding="async"></div>
        <div class="ig-ins__logo"><img src="/assets/img/insurences-5-1.webp" alt="Molina Healthcare and UniCare" width="200" height="220" loading="lazy" decoding="async"></div>
        <div class="ig-ins__logo"><img src="/assets/img/insurences-3.webp" alt="Aetna and Delta Dental" width="200" height="220" loading="lazy" decoding="async"></div>
        <div class="ig-ins__logo"><img src="/assets/img/insurences-2.webp" alt="Medicaid and Careington" width="200" height="220" loading="lazy" decoding="async"></div>
        <div class="ig-ins__logo"><img src="/assets/img/insurences-1.webp" alt="All Kids and Unum" width="200" height="220" loading="lazy" decoding="async"></div>
        <div class="ig-ins__logo"><img src="/assets/img/insurences-7.webp" alt="IlliniCare Health and Colonial Life" width="200" height="220" loading="lazy" decoding="async"></div>
        <div class="ig-ins__logo"><img src="/assets/img/insurences-6.webp" alt="CountyCare Health Plan and AlwaysCare" width="200" height="220" loading="lazy" decoding="async"></div>
      </div>
    </div>

    <div class="ig-wrap">
      <div class="ig-ins__foot">
        <p class="ig-ins__note">Insurance coverage varies by plan. Benefits and eligibility should be confirmed before treatment.</p>
      </div>
    </div>
  </section>


  <!-- ==========================================================
       6 + 7. WE ARE A COMMUNITY  /  PATIENTS WITH REASONS TO SMILE
       (one full-width band, split 38.5 / 61.5 like the reference)
       ========================================================== -->
  <section class="ig-band">

    <!-- ---------- LEFT: community ---------- -->
    <div class="ig-comm">
      <div class="ig-comm__media">
        <img src="/assets/img/IMG_20260814_125736.jpg" alt="" width="1920" height="1080" loading="lazy" decoding="async">
      </div>

      <div class="ig-comm__inner">
        <span class="ig-comm__mark">
          <img src="/assets/img/ignitelogo.png"
               alt="Ignite Orthodontics" width="300" height="92" loading="lazy" decoding="async">
        </span>
        <h2>We Are A<em>Community.</em></h2>
        <a class="ig-btn ig-btn--primary" href="/about-us/">Learn More About Ignite Orthodontics</a>
      </div>
    </div>

    <!-- ---------- RIGHT: reviews collage ---------- -->
    <div class="ig-test">

      <div class="ig-test__head">
        <span class="ig-kicker">Patients With Reasons to Smile</span>
        <h2>See Why Patients <em>Choose Ignite.</em></h2>
      </div>

      <!-- EDIT: replace with real Google reviews -->
      <div class="ig-test__collage">

        <article class="ig-card-q ig-card-q--a">
          <div class="ig-card-q__stars" aria-label="5 out of 5"><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg></div>
          <div class="ig-card-q__who">
            <span class="ig-card-q__av"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 12a5 5 0 1 0 0-10 5 5 0 0 0 0 10zm0 2c-4 0-8 2-8 5v1h16v-1c0-3-4-5-8-5z"/></svg></span>
            <div><h4>Sarah M.</h4></div>
          </div>
          <p class="ig-card-q__text">&ldquo;From the first consultation, everyone made us feel comfortable. They explained my daughter&rsquo;s treatment clearly, answered all our questions, and made the whole process much easier than we expected.&rdquo;</p>
        </article>

        <article class="ig-card-q ig-card-q--b">
          <div class="ig-card-q__stars" aria-label="5 out of 5"><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg></div>
          <div class="ig-card-q__who">
            <span class="ig-card-q__av"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 12a5 5 0 1 0 0-10 5 5 0 0 0 0 10zm0 2c-4 0-8 2-8 5v1h16v-1c0-3-4-5-8-5z"/></svg></span>
            <div><h4>Marcus T.</h4></div>
          </div>
          <p class="ig-card-q__text">&ldquo;I was nervous about getting braces as an adult, but the team made me feel completely comfortable. They took the time to explain my options and helped me choose a treatment that fit my needs and budget.&rdquo;</p>
        </article>

        <article class="ig-card-q ig-card-q--c">
          <div class="ig-card-q__stars" aria-label="5 out of 5"><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg></div>
          <div class="ig-card-q__who">
            <span class="ig-card-q__av"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 12a5 5 0 1 0 0-10 5 5 0 0 0 0 10zm0 2c-4 0-8 2-8 5v1h16v-1c0-3-4-5-8-5z"/></svg></span>
            <div><h4>Jennifer R.</h4></div>
          </div>
          <p class="ig-card-q__text">&ldquo;The staff is friendly, appointments are easy to manage, and we always know what to expect next. My son has had a great experience with his treatment so far.&rdquo;</p>
        </article>

        <article class="ig-card-q ig-card-q--d">
          <div class="ig-card-q__stars" aria-label="5 out of 5"><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg></div>
          <div class="ig-card-q__who">
            <span class="ig-card-q__av"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 12a5 5 0 1 0 0-10 5 5 0 0 0 0 10zm0 2c-4 0-8 2-8 5v1h16v-1c0-3-4-5-8-5z"/></svg></span>
            <div><h4>David K.</h4></div>
          </div>
          <p class="ig-card-q__text">&ldquo;Everyone at Ignite has been professional, welcoming, and easy to talk to. I really appreciated how clearly they explained the treatment and payment options before we got started.&rdquo;</p>
        </article>

      </div>

      <div class="ig-test__foot">
        <a class="ig-btn ig-btn--navy" href="/testimonials/">View More Reviews</a>
      </div>
    </div>
  </section>


  <?php require APP . '/views/partials/finder.php'; ?>


  <!-- ==========================================================
       9. FINAL CTA
       ========================================================== -->
  <section class="ig-sec ig-final">
    <div class="ig-wrap">
      <span class="ig-kicker">Ignite Orthodontics</span>
      <h2>Your Best Smile Starts With <em>a Conversation.</em></h2>
      <div class="ig-btns" style="justify-content:center;">
        <a class="ig-btn ig-btn--primary" href="<?= e(booking_url()) ?>">Schedule a Consultation</a>
        <a class="ig-btn ig-btn--white" href="tel:<?= e(cfg('phone_tel')) ?>">Call <?= e(cfg('phone')) ?></a>
      </div>
    </div>
  </section>

</div>
