<?php /* GENERATED by tools/extract.php from kids-braces-page-layout.html. Edit the source file and re-run; changes here are overwritten. */ ?>
<div class="kp">


    <!-- ============================================================
         HERO SECTION
    ============================================================ -->
    <section class="hero">
        <div class="container hero-grid">
            <div class="hero-content">
                <h1>Creating Healthy, Confident <span>Smiles for Kids</span> &amp; Teens</h1>
                <p>Gentle, fun, and stress-free orthodontic care designed specifically for children. Guide early jaw growth, fix crowding, and build a lifetime of confidence!</p>
                <div class="hero-actions">
                    <a href="#" data-popup="true" class="btn btn-primary">Book Free Consultation</a>
                    <a href="tel:<?= e(cfg('phone_tel')) ?>" class="btn btn-outline" style="border-color: rgba(255,255,255,0.4); color: white;">Call <?= e(cfg('phone')) ?></a>
                </div>
                <div class="hero-trust-bar">
                    <div class="trust-item">
                        <svg viewBox="0 0 24 24"><path d="M12 2L15.09 8.26L22 9.27L17 14.14L18.18 21.02L12 17.77L5.82 21.02L7 14.14L2 9.27L8.91 8.26L12 2Z"/></svg>
                        <span>0% Interest Payment Plans</span>
                    </div>
                    <div class="trust-item">
                        <svg viewBox="0 0 24 24"><path d="M12 2L15.09 8.26L22 9.27L17 14.14L18.18 21.02L12 17.77L5.82 21.02L7 14.14L2 9.27L8.91 8.26L12 2Z"/></svg>
                        <span>Most Insurances Accepted</span>
                    </div>
                </div>
            </div>

            <!-- Hero Image Box -->
            <div class="hero-image-box">
                <img src="/assets/img/istockphoto-1202583861-612x612-1.webp" alt="Kids Braces Smile Consultation" class="hero-img">
            </div>
        </div>
    </section>

    <!-- ============================================================
         SECTION 2: WHY AGE 7? (EARLY ASSESSMENT)
    ============================================================ -->
    <section class="early-assessment" id="why-age-7">
        <div class="container">
            <div class="section-header">
                <span class="badge-pill">Early Growth Guidance</span>
                <h2>Why the AAO Recommends a Checkup by Age 7</h2>
                <p>By age 7, a child has a mix of baby teeth and adult teeth, allowing orthodontists to catch potential jaw and bite issues before they become complex problems.</p>
            </div>

            <div class="early-grid">
                <div class="early-card-highlight">
                    <h3>Benefits of Interceptive Treatment</h3>
                    <p>Early treatment (Phase 1) works with your child's natural growth spurts to achieve optimal facial symmetry and jaw expansion.</p>
                    <ul class="benefit-checklist">
                        <li>Guides jaw growth for proper facial structure</li>
                        <li>Creates room for crowded, emerging adult teeth</li>
                        <li>Fixes thumb-sucking and tongue-thrust habits</li>
                        <li>Reduces the need to extract permanent teeth later</li>
                        <li>Simplifies future comprehensive treatment (Phase 2)</li>
                    </ul>
                </div>

                <div class="early-right-col">
                    <div style="margin-bottom: 24px; border-radius: var(--radius-lg); overflow: hidden; box-shadow: var(--shadow-md);">
                        <img src="/assets/img/shutterstock_2331223617-min.jpg" alt="Child Orthodontic Examination" style="width: 100%; height: 200px; object-fit: cover; display: block;">
                    </div>
                    <div class="phases-comparison">
                        <div class="phase-box">
                            <span class="phase-tag">Phase 1 (Ages 7–10)</span>
                            <h4>Preventative Guidance</h4>
                            <p>Focuses on jaw expansion and space maintenance while your child is actively growing.</p>
                        </div>
                        <div class="phase-box">
                            <span class="phase-tag">Phase 2 (Ages 11+)</span>
                            <h4>Comprehensive Alignment</h4>
                            <p>Full braces or clear aligners once permanent adult teeth erupt to finalize alignment.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- ============================================================
         SECTION 3: TREATMENT OPTIONS FOR KIDS & TEENS
    ============================================================ -->
    <section class="treatments-section" id="treatments">
        <div class="container">
            <div class="section-header">
                <span class="badge-pill">Tailored Treatments</span>
                <h2>Orthodontic Options Designed for Kids</h2>
                <p>Every child’s smile is unique. We offer modern, comfortable treatment options that match your child’s lifestyle and aesthetic preferences.</p>
            </div>

            <div class="treatments-grid">
                <!-- Option 1: White Card -->
                <div class="treatment-card card-white">
                    <div>
                        <h3>Metal Braces</h3>
                        <p>Durable, precise, and fun! Kids love choosing custom colored elastics at every appointment.</p>
                    </div>
                    <span class="tag-accent">Most Popular for Kids</span>
                </div>

                <!-- Option 2: Brand Orange Card -->
                <div class="treatment-card card-orange">
                    <div>
                        <h3>Clear Ceramic Braces</h3>
                        <p>Blends naturally with tooth color for a discreet look that image-conscious teens prefer.</p>
                    </div>
                    <span class="tag-accent">Discreet &amp; Aesthetic</span>
                </div>

                <!-- Option 3: White Card -->
                <div class="treatment-card card-white">
                    <div>
                        <h3>Invisalign® First</h3>
                        <p>Removable, clear aligners engineered specifically for growing children with mixed baby and adult teeth.</p>
                    </div>
                    <span class="tag-accent">No Food Restrictions</span>
                </div>

                <!-- Option 4: Brand Orange Card -->
                <div class="treatment-card card-orange">
                    <div>
                        <h3>Palatal Expanders</h3>
                        <p>Gentle appliances that widen narrow upper jaws, alleviating severe crowding and improving breathing.</p>
                    </div>
                    <span class="tag-accent">Early Growth Helper</span>
                </div>
            </div>
        </div>
    </section>

    <!-- ============================================================
         SECTION 4: KIDS STRESS-FREE EXPERIENCE (STEPS)
    ============================================================ -->
    <section class="experience-section" id="kids-experience">
        <div class="container">
            <div class="section-header">
                <span class="badge-pill">Parent &amp; Kid Friendly</span>
                <h2>What to Expect: A Stress-Free Journey</h2>
                <p>We make orthodontic appointments welcoming, engaging, and fun for your child from day one.</p>
            </div>

            <div class="experience-grid" style="display: grid; grid-template-columns: 1.1fr 0.9fr; gap: 40px; align-items: center;">
                <!-- Left: 4 Step Cards Grid -->
                <div class="steps-wrapper" style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px;">
                    <div class="step-card">
                        <div class="step-number">1</div>
                        <h4>Warm Welcome</h4>
                        <p>Friendly staff, comfortable environment, and zero pressure. We explain everything in kid-friendly terms.</p>
                    </div>
                    <div class="step-card">
                        <div class="step-number">2</div>
                        <h4>3D Digital Scans</h4>
                        <p>No gooey, uncomfortable mold impressions! Our fast 3D digital scanner creates a precise digital model of teeth.</p>
                    </div>
                    <div class="step-card">
                        <div class="step-number">3</div>
                        <h4>Personalized Plan</h4>
                        <p>Our orthodontists design a tailored roadmap with clear timelines, transparent pricing, and flexible payment plans.</p>
                    </div>
                    <div class="step-card">
                        <div class="step-number">4</div>
                        <h4>Pick Color Bands!</h4>
                        <p>Your child gets to personalize their braces with their favorite sports team, holiday, or school colors.</p>
                    </div>
                </div>

                <!-- Right: Experience Feature Image Card -->
                <div style="border-radius: var(--radius-lg); overflow: hidden; box-shadow: var(--shadow-md); height: 100%; min-height: 380px;">
                    <img src="/assets/img/istockphoto-2166449878-612x612-1.webp" alt="Kids Orthodontic Care Experience" style="width: 100%; height: 100%; object-fit: cover; display: block;">
                </div>
            </div>
        </div>
    </section>

    <!-- ============================================================
         SECTION 5: FINANCIAL & AFFORDABILITY
    ============================================================ -->
    <section class="affordability-section" id="affordability">
        <div class="container">
            <div class="section-header text-center">
                <span class="badge-pill" style="background: rgba(255,255,255,0.15); color: #60A5FA;">Financial Peace of Mind</span>
                <h2 style="color: white;">Making Kids Braces Affordable for Every Family</h2>
                <p style="color: rgba(255,255,255,0.85);">We believe every child deserves a healthy smile. We work directly with your insurance and offer low monthly payment options.</p>
            </div>

            <div class="afford-horizontal-grid" style="display: grid; grid-template-columns: 0.9fr 1.1fr; gap: 40px; align-items: center; margin-top: 40px;">
                <!-- Left: Image Card FIRST -->
                <div style="border-radius: var(--radius-lg); overflow: hidden; box-shadow: var(--shadow-md); height: 100%; min-height: 360px;">
                    <img src="/assets/img/istockphoto-1367329991-612x612-1.webp" alt="Affordable Orthodontics for Kids" style="width: 100%; height: 100%; object-fit: cover; display: block;">
                </div>

                <!-- Right: Content Cards & CTA -->
                <div style="display: flex; flex-direction: column; gap: 16px;">
                    <div class="afford-box" style="text-align: left; padding: 22px 24px;">
                        <h3 style="font-size: 1.4rem; margin-bottom: 6px;">$0 Down Options</h3>
                        <p style="font-size: 0.92rem; margin: 0;">Flexible low monthly payment plans with zero interest options to fit your family budget.</p>
                    </div>
                    <div class="afford-box" style="text-align: left; padding: 22px 24px;">
                        <h3 style="font-size: 1.4rem; margin-bottom: 6px;">Insurance Maximized</h3>
                        <p style="font-size: 0.92rem; margin: 0;">We accept most dental PPO plans and file claims on your behalf to maximize your orthodontic benefits.</p>
                    </div>
                    <div class="afford-box" style="text-align: left; padding: 22px 24px;">
                        <h3 style="font-size: 1.4rem; margin-bottom: 6px;">Free Consultation</h3>
                        <p style="font-size: 0.92rem; margin: 0;">Your child's first consultation, X-rays, and 3D scans are 100% complimentary with no obligation.</p>
                    </div>
                    <div style="margin-top: 10px;">
                        <a href="#" data-popup="true" class="btn btn-primary" style="width: 100%;">Check Financial Options</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- ============================================================
         SECTION 6: FREQUENTLY ASKED QUESTIONS
    ============================================================ -->
    <section class="faq-section" id="faq">
        <div class="container">
            <div class="section-header">
                <span class="badge-pill">Parent FAQs</span>
                <h2>Frequently Asked Questions</h2>
                <p>Have questions about your child's orthodontic care? Here are answers to common parent inquiries.</p>
            </div>

            <div class="faq-container">
                <div class="faq-item active">
                    <button class="faq-question" onclick="toggleFaq(this)">
                        At what age should my child first see an orthodontist?
                        <span class="faq-icon">+</span>
                    </button>
                    <div class="faq-answer">
                        The American Association of Orthodontists (AAO) recommends that every child have their first orthodontic evaluation by age 7. At this stage, early jaw problems and crowding can be identified and corrected before permanent teeth fully erupt.
                    </div>
                </div>

                <div class="faq-item">
                    <button class="faq-question" onclick="toggleFaq(this)">
                        Does early treatment (Phase 1) mean my child won't need braces later?
                        <span class="faq-icon">+</span>
                    </button>
                    <div class="faq-answer">
                        Phase 1 prepares the jaw and creates necessary space for permanent teeth to erupt properly. While many children still require Phase 2 (full braces or aligners) in their teen years, Phase 1 makes Phase 2 significantly shorter, easier, and less invasive.
                    </div>
                </div>

                <div class="faq-item">
                    <button class="faq-question" onclick="toggleFaq(this)">
                        Do braces hurt when first put on?
                        <span class="faq-icon">+</span>
                    </button>
                    <div class="faq-answer">
                        Putting braces on does not hurt at all! Your child may feel mild soreness or pressure for a few days after adjustments as teeth begin moving. Over-the-counter pain relievers and soft foods easily keep them comfortable.
                    </div>
                </div>

                <div class="faq-item">
                    <button class="faq-question" onclick="toggleFaq(this)">
                        Can my child still play sports or musical instruments?
                        <span class="faq-icon">+</span>
                    </button>
                    <div class="faq-answer">
                        Absolutely! Children with braces can participate in all sports and play wind or brass instruments. We recommend wearing a custom orthodontic mouthguard during sports to protect their teeth and lips.
                    </div>
                </div>

                <div class="faq-item">
                    <button class="faq-question" onclick="toggleFaq(this)">
                        How much do braces for kids cost?
                        <span class="faq-icon">+</span>
                    </button>
                    <div class="faq-answer">
                        Treatment costs vary based on your child's specific alignment needs and treatment duration. We offer free consultations, accept dental insurance, and provide flexible 0% interest monthly payment options to ensure braces fit comfortably within your budget.
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- ============================================================
         MODAL POPUP
    ============================================================ -->
    <div class="modal-overlay" id="booking-modal">
        <div class="modal-box">
            <button class="modal-close" id="modal-close-btn" aria-label="Close">&times;</button>
            <div id="modal-initial-view">
                <h2 class="modal-title">Select Your Location</h2>
                <p class="modal-sub">Choose your nearest Ignite Orthodontics office to schedule your child's free consultation.</p>
                <div class="modal-locs">
<?php foreach (locations() as $l): ?>
                    <a href="/locations/<?= e($l['slug']) ?>/#ig-consult" class="modal-loc"><?= e($l['name']) ?></a>
<?php endforeach; ?>
                </div>
            </div>
            <div id="modal-success-view" style="display: none; padding: 20px 0;">
                <div style="width: 60px; height: 60px; background: rgba(244, 116, 33, 0.15); color: var(--brand-accent); border-radius: 50%; display: flex; align-items: center; justify-content: center; margin: 0 auto 16px; font-size: 1.8rem; font-weight: bold;">✓</div>
                <h3 style="color: var(--brand-navy); font-size: 1.5rem; margin-bottom: 8px;">Location Selected!</h3>
                <p style="color: var(--text-muted); font-size: 0.95rem;">Thank you! Our team will reach out shortly to confirm your consultation at our <strong id="selected-loc-name" style="color: var(--brand-accent);"></strong> office.</p>
            </div>
        </div>
    </div>
</div>
