<?php /* GENERATED by tools/extract.php from location-preview.html. Edit the source file and re-run; changes here are overwritten. */ ?>
<div class="ig-locpage">

  <!-- ==========================================================
       1. HERO
       ========================================================== -->
  <section class="ig-lhero">
    <div class="ig-lhero__media">
      <!-- EDIT: exterior photo of this office -->
      <img src="/assets/img/invisalign-braces-scaled.jpg"
           alt="" width="1600" height="1067" fetchpriority="high" decoding="async">
    </div>

    <div class="ig-wrap">
      <div class="ig-lhero__inner">
        <div class="ig-lhero__copy">
          <span class="ig-lhero__pill">Transform Your Smile With The Best Orthodontists in <?= e($loc['name']) ?></span>

          <h1>Ignite Orthodontics <em><?= e($loc['name']) ?></em></h1>

          <p class="ig-lhero__addr">
            <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 2C8.1 2 5 5.1 5 9c0 5.2 7 13 7 13s7-7.8 7-13c0-3.9-3.1-7-7-7zm0 9.5A2.5 2.5 0 1 1 12 6.5a2.5 2.5 0 0 1 0 5z"/></svg>
            <?= e($loc['address_full']) ?>
          </p>

          <div class="ig-btns ig-btns--c">
            <a class="ig-btn ig-btn--primary" href="#ig-consult">Schedule Now</a>
            <a class="ig-btn ig-btn--white" href="tel:<?= e($loc['tel']) ?>">Call Now</a>
          </div>
        </div>
      </div>
    </div>

    <!-- trust card — hangs below the photo into the next section -->
    <div class="ig-trustwrap">
      <div class="ig-trustcard">
        <!-- EDIT: real patient count -->
        <p class="ig-trustcard__banner">Over 10,000 Happy Patients</p>

        <!-- EDIT: swap the wordmarks for real platform logos, and set true ratings -->
        <div class="ig-trustcard__logos">
        <div class="ig-plat">
          <span class="ig-plat__logo">
            <span class="ig-plat__g"><i class="b">G</i><i class="r">o</i><i class="y">o</i><i class="b">g</i><i class="g">l</i><i class="r">e</i></span>
          </span>
          <span class="ig-plat__rate">Rating <span class="ig-plat__stars"><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg></span></span>
        </div>

        <div class="ig-plat ig-plat--bing">
          <span class="ig-plat__logo">
            <svg viewBox="0 0 24 32" aria-hidden="true">
              <defs><linearGradient id="igBing" x1="0" y1="0" x2="1" y2="1">
                <stop offset="0" stop-color="#00CACD"/><stop offset="1" stop-color="#0A80CE"/>
              </linearGradient></defs>
              <path fill="url(#igBing)" d="M2 0l6 2.2v20.6l8.4-4.9-4.1-1.9-2.6-6.6L22 13.7v7.8L8 32l-6-3.4z"/>
            </svg>
            <span class="ig-plat__word ig-plat__word--bing">Bing</span>
          </span>
          <span class="ig-plat__rate">Rating <span class="ig-plat__stars"><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg></span></span>
        </div>

        <div class="ig-plat ig-plat--hg">
          <span class="ig-plat__logo">
            <svg viewBox="0 0 32 28" aria-hidden="true">
              <path fill="#0B4DA2" d="M16 27S2 18.6 2 10.6A6.6 6.6 0 0 1 16 6.8 6.6 6.6 0 0 1 30 10.6C30 18.6 16 27 16 27z"/>
              <path fill="#fff" d="M9.6 12.6 8 14.2l5.4 5.4L24 9l-1.7-1.7-8.9 8.9z"/>
            </svg>
            <span class="ig-plat__word ig-plat__word--hg">healthgrades.</span>
          </span>
          <span class="ig-plat__rate">Rating <span class="ig-plat__stars"><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg></span></span>
        </div>

        <div class="ig-plat ig-plat--yelp">
          <span class="ig-plat__logo">
            <span class="ig-plat__word ig-plat__word--yelp">yelp</span>
            <svg viewBox="0 0 24 24" aria-hidden="true">
              <path fill="#FF1A1A" d="M12 1.4l1.7 6.9 4.8-4.1-2.6 6.3 6.9-1.6-6 3.8 6 3.8-6.9-1.6 2.6 6.3-4.8-4.1L12 22.6l-1.7-6.9-4.8 4.1 2.6-6.3-6.9 1.6 6-3.8-6-3.8 6.9 1.6-2.6-6.3 4.8 4.1z"/>
            </svg>
          </span>
          <span class="ig-plat__rate">Rating <span class="ig-plat__stars"><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg><svg viewBox="0 0 24 24" fill="currentColor"><path d="m12 17.3-6.2 3.7 1.7-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.5 4.8 1.7 7z"/></svg></span></span>
        </div>
        </div>
      </div>
    </div>
  </section>


  <!-- ==========================================================
       2. HOW WE STAND OUT
       ========================================================== -->
  <section class="ig-sec ig-sec--after-hero">
    <div class="ig-wrap">
      <div class="ig-head">
        <span class="ig-kicker">The Orthodontist In <?= e($loc['name']) ?> Families Recommend</span>
        <h2 class="ig-h2">How We <em>Stand Out</em></h2>
        <p class="ig-lead ig-standout__lead">Our experienced orthodontist in <?= e($loc['name']) ?> specializes in <a href="/clear-aligners/">Invisalign&reg;</a>, 3M&trade; Clear Aligners, and braces. With advanced training and years of patient care, we create personalized treatment plans that deliver safe and effective results. We&rsquo;re proud to be recognized in the <?= e($loc['name']) ?> community for our <a href="/about-us/">expertise</a>, transparency, and compassionate care, helping families achieve healthier, more confident smiles.</p>
      </div>
    </div>
  </section>

  <!-- cards straddle the seam: pulled up into the pale band above -->
  <section class="ig-sec ig-standout">
    <div class="ig-wrap">
      <!-- EDIT: replace with photography for this office -->
      <div class="ig-standout__grid">
        <a class="ig-so" href="#ig-consult">
          <img src="/assets/img/01-image.webp" alt="Patient wearing metal braces" width="288" height="467" loading="lazy" decoding="async">
          <div class="ig-so__inner">
            <h3 class="ig-so__title">Treatment<br>Options</h3>
            <p class="ig-so__text">We offer a variety of effective treatment options, including traditional metal braces, Invisalign&reg;, 3M clarity aligners and other innovative solutions. Our focus is on providing the best services from local orthodontists who prioritize your needs.</p>
          </div>
        </a>

        <a class="ig-so" href="#ig-consult">
          <img src="/assets/img/02-image.webp" alt="The Ignite Orthodontics team" width="288" height="467" loading="lazy" decoding="async">
          <div class="ig-so__inner">
            <h3 class="ig-so__title">Experienced<br>Care</h3>
            <p class="ig-so__text">Our board-certified orthodontists have guided thousands of patients from first consultation to finished smile. Every plan is designed, monitored and adjusted by a specialist &mdash; never handed off.</p>
          </div>
        </a>

        <a class="ig-so" href="#ig-consult">
          <img src="/assets/img/03-image.webp" alt="Patient with a savings jar" width="288" height="467" loading="lazy" decoding="async">
          <div class="ig-so__inner">
            <h3 class="ig-so__title">Affordable<br>Solutions</h3>
            <p class="ig-so__text">Interest-free in-house payment plans, clear pricing and no unexpected costs. We accept most major insurance plans and verify your benefits before treatment begins, so you always know where you stand.</p>
          </div>
        </a>

        <a class="ig-so" href="#ig-consult">
          <img src="/assets/img/img1-1.jpg" alt="Adult patient with ceramic braces" width="288" height="467" loading="lazy" decoding="async">
          <div class="ig-so__inner">
            <h3 class="ig-so__title">Orthodontic Care For<br>All Ages</h3>
            <p class="ig-so__text">From a child&rsquo;s first evaluation through teen and adult treatment, we tailor care to every stage of life. It is never too early &mdash; or too late &mdash; to start.</p>
          </div>
        </a>

      </div>
    </div>
  </section>


  <!-- ==========================================================
       3. DISCOUNTS & OFFERS
       ========================================================== -->
  <section class="ig-sec">
    <div class="ig-wrap">
      <div class="ig-head">
        <span class="ig-kicker">Affordable Orthodontist In <?= e($loc['name']) ?></span>
        <h2 class="ig-h2">Discounts And <em>Offers</em></h2>
        <p class="ig-lead ig-standout__lead">At Ignite Orthodontics <?= e($loc['name']) ?>, we combine experience, expertise, and transparency to make orthodontic care accessible for every family. With <a href="/insurance-financing/">flexible payment plans</a>, clear pricing, and no hidden fees, you can trust us to deliver affordable braces, <a href="/clear-aligners/">clear aligners</a>, and Invisalign&reg;, without compromising on quality.</p>
        <p class="ig-lead ig-standout__lead" style="margin-top:1.4em;">Schedule your no-cost consultation today to explore the best offer for your smile journey.</p>
      </div>

      <!-- EDIT: all pricing is placeholder — set Ignite's real offers -->
      <div class="ig-offers">
        <div class="ig-offer">
          <div class="ig-offer__bg"><img src="/assets/img/happy-family.jpg" alt="" width="288" height="467" loading="lazy" decoding="async"></div>
          <div class="ig-offer__av"><img src="/assets/img/happy-family.jpg" alt="Smiling patient with braces" width="288" height="467" loading="lazy" decoding="async"></div>
          <h3 class="ig-offer__title">Braces from<br>$99<sup>*</sup>/Month</h3>
          <p class="ig-offer__desc">Braces from just $99* per month. Offer terms and eligibility apply.</p>
          <p class="ig-offer__terms">Terms and Conditions</p>
        </div>

        <div class="ig-offer">
          <div class="ig-offer__bg"><img src="/assets/img/hero2.png" alt="" width="288" height="467" loading="lazy" decoding="async"></div>
          <div class="ig-offer__av"><img src="/assets/img/hero2.png" alt="Patient holding a clear aligner" width="288" height="467" loading="lazy" decoding="async"></div>
          <h3 class="ig-offer__title">Clear Aligners from<br>$185<sup>*</sup>/Month</h3>
          <p class="ig-offer__desc">Clear aligners from $185* per month. Offer terms and eligibility apply.</p>
          <p class="ig-offer__terms">Terms and Conditions</p>
        </div>

        <div class="ig-offer">
          <div class="ig-offer__bg"><img src="/assets/img/03-image.webp" alt="" width="288" height="467" loading="lazy" decoding="async"></div>
          <div class="ig-offer__av"><img src="/assets/img/03-image.webp" alt="Saving for orthodontic treatment" width="288" height="467" loading="lazy" decoding="async"></div>
          <h3 class="ig-offer__title">Interest-Free<br>Payment Plans</h3>
          <p class="ig-offer__desc">Enjoy 0% APR with Ignite Orthodontics&rsquo; in-house financing plans.</p>
          <p class="ig-offer__terms">Terms and Conditions</p>
        </div>

      </div>

      <div class="ig-btns ig-btns--c" style="margin-top:clamp(30px,3.6vw,64px);">
        <a class="ig-btn ig-btn--primary" href="#ig-consult">Schedule Now</a>
        <a class="ig-btn ig-btn--navy" href="tel:<?= e($loc['tel']) ?>">Call Now</a>
      </div>
    </div>
  </section>


  <!-- ==========================================================
       4. TREATMENT OPTIONS
       ========================================================== -->
  <section class="ig-sec">
    <div class="ig-wrap">
      <div class="ig-head">
        <span class="ig-kicker">Choose Your Style, Enjoy Your Smile</span>
        <h2 class="ig-h2">Best Orthodontic Treatment In <em><?= e($loc['name']) ?></em></h2>
        <p class="ig-lead">Make a lasting impression with your dream smile. We offer a full range of treatment options for children, teens and adults.</p>
      </div>

      <div class="ig-treats">
        <a class="ig-treat" href="/types-of-braces/">
          <div class="ig-treat__img">
            <img src="/assets/img/01-image.webp" alt="Traditional metal braces" width="288" height="467" loading="lazy" decoding="async">
          </div>
          <div class="ig-treat__body">
            <h3>Metal Braces</h3>
            <p>The most cost-effective way to correct alignment, using durable stainless steel brackets and archwires.</p>
          </div>
        </a>
        <a class="ig-treat" href="/gold-braces/">
          <div class="ig-treat__img">
            <img src="/assets/img/02-image.webp" alt="Gold braces" width="288" height="467" loading="lazy" decoding="async">
          </div>
          <div class="ig-treat__body">
            <h3>Gold Braces</h3>
            <p>All the reliability of traditional braces, finished with gold-polished brackets for a warmer look.</p>
          </div>
        </a>
        <a class="ig-treat" href="/clear-aligners/">
          <div class="ig-treat__img">
            <img src="/assets/img/03-image.webp" alt="Clear aligners" width="288" height="467" loading="lazy" decoding="async">
          </div>
          <div class="ig-treat__body">
            <h3>Clear Aligners</h3>
            <p>Our best option for virtually invisible treatment, including Invisalign&reg; and 3M clear aligners.</p>
          </div>
        </a>
        <a class="ig-treat" href="/ceramic-braces/">
          <div class="ig-treat__img">
            <img src="/assets/img/img1-1.jpg" alt="Ceramic braces" width="288" height="467" loading="lazy" decoding="async">
          </div>
          <div class="ig-treat__body">
            <h3>Ceramic Braces</h3>
            <p>Tooth-coloured brackets that reposition teeth discreetly, blending in with your natural smile.</p>
          </div>
        </a>
      </div>

      <div class="ig-btns ig-btns--c" style="margin-top:clamp(28px,3.2vw,44px);">
        <a class="ig-btn ig-btn--primary" href="#ig-consult">Schedule Now</a>
        <a class="ig-btn ig-btn--out" href="tel:<?= e($loc['tel']) ?>">Call Now</a>
      </div>
    </div>
  </section>


  <!-- ==========================================================
       6. FAMILY-FRIENDLY CARE
       ========================================================== -->
  <section class="ig-sec">
    <div class="ig-wrap">
      <div class="ig-head">
        <span class="ig-kicker">Smile With Confidence At Every Stage Of Life</span>
        <h2 class="ig-h2">Family-Friendly Orthodontist in <em><?= e($loc['name']) ?></em></h2>
        <p class="ig-lead">Personalised care for children, teens and adults — because the right treatment depends on where you are in life.</p>
      </div>

      <div class="ig-ages">
        <div class="ig-age">
          <img src="/assets/img/01-image.webp" alt="Orthodontic care for kids" width="288" height="467" loading="lazy" decoding="async">
          <div class="ig-age__body">
            <h3>Kids</h3>
            <p>We focus on early intervention, guiding growth so later treatment is shorter and simpler.</p>
            <a class="ig-btn ig-btn--primary" href="#ig-consult">Schedule Now</a>
          </div>
        </div>
        <div class="ig-age">
          <img src="/assets/img/02-image.webp" alt="Orthodontic care for teens" width="288" height="467" loading="lazy" decoding="async">
          <div class="ig-age__body">
            <h3>Teens</h3>
            <p>Choose from metal braces in your own colours or virtually invisible clear aligners.</p>
            <a class="ig-btn ig-btn--primary" href="#ig-consult">Schedule Now</a>
          </div>
        </div>
        <div class="ig-age">
          <img src="/assets/img/03-image.webp" alt="Orthodontic care for adults" width="288" height="467" loading="lazy" decoding="async">
          <div class="ig-age__body">
            <h3>Adults</h3>
            <p>It's never too late. Discreet treatment options fit around work and everyday life.</p>
            <a class="ig-btn ig-btn--primary" href="#ig-consult">Schedule Now</a>
          </div>
        </div>
      </div>
    </div>
  </section>


  <!-- ==========================================================
       7. MID-PAGE CTA
       ========================================================== -->
  <section class="ig-sec ig-cta">
    <div class="ig-wrap">
      <h2>Experience the Best in Orthodontic Care in <?= e($loc['name']) ?> &mdash; <em>Schedule A No-Cost Consultation Now!</em></h2>
      <p>Your first visit includes a full exam, x-rays and a personalised treatment plan, at no charge and with no obligation.</p>
      <div class="ig-btns ig-btns--c">
        <a class="ig-btn ig-btn--primary" href="#ig-consult">Schedule Now</a>
        <a class="ig-btn ig-btn--white" href="tel:<?= e($loc['tel']) ?>">Call <?= e($loc['phone']) ?></a>
      </div>
    </div>
  </section>


  <!-- ==========================================================
       8. BOOK A NO-COST CONSULTATION
       ========================================================== -->
  <?php $ctaImage = '/assets/img/invisalign-braces-scaled.jpg'; $ctaPhone = $loc['phone']; $ctaTel = $loc['tel']; require APP . '/views/partials/consult-cta.php'; ?>


    <!-- ==========================================================
       14. CONTACT, HOURS & MAP
       ========================================================== -->
  <section class="ig-sec ig-sec--tint">
    <div class="ig-wrap">
      <div class="ig-mapwrap">

        <div>
          <span class="ig-kicker">Our Location</span>
          <h2 class="ig-h2">Ignite Orthodontics <em><?= e($loc['name']) ?></em></h2>

          <ul class="ig-info">
            <li>
              <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 2C8.1 2 5 5.1 5 9c0 5.2 7 13 7 13s7-7.8 7-13c0-3.9-3.1-7-7-7zm0 9.5A2.5 2.5 0 1 1 12 6.5a2.5 2.5 0 0 1 0 5z"/></svg>
              <span><?= e($loc['address_full']) ?></span>
            </li>
            <li>
              <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M6.6 10.8c1.4 2.8 3.8 5.1 6.6 6.6l2.2-2.2c.3-.3.7-.4 1-.2 1.2.4 2.4.6 3.6.6.6 0 1 .4 1 1V20c0 .6-.4 1-1 1-9.4 0-17-7.6-17-17 0-.6.4-1 1-1h3.5c.6 0 1 .4 1 1 0 1.3.2 2.5.6 3.6.1.3 0 .7-.2 1l-2.3 2.2z"/></svg>
              <span><a href="tel:<?= e($loc['tel']) ?>"><?= e($loc['phone']) ?></a></span>
            </li>
            <li>
              <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M20 4H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2zm0 4.2-8 4.8-8-4.8V6l8 4.8L20 6v2.2z"/></svg>
              <span><a href="mailto:<?= e($loc['email']) ?>"><?= e($loc['email']) ?></a></span>
            </li>
          </ul>

          <p class="ig-lead" style="margin-top:18px;">Call the office for current hours and appointment availability.</p>
        </div>

        <div class="ig-mapbox">
          <iframe src="https://maps.google.com/maps?q=<?= urlencode($loc['map_q']) ?>&amp;z=15&amp;output=embed"
                  title="Map to Ignite Orthodontics <?= e($loc['name']) ?>"
                  loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe>
        </div>
      </div>
    </div>
  </section>


  <!-- ==========================================================
       15. CONDITIONS WE TREAT
       ========================================================== -->
  <section class="ig-sec">
    <div class="ig-wrap">
      <div class="ig-head">
        <span class="ig-kicker">Orthodontic Conditions &amp; Solutions</span>
        <h2 class="ig-h2">Personalised Orthodontic Treatment in <em><?= e($loc['name']) ?></em></h2>
        <p class="ig-lead">Don't let misaligned teeth or jaws affect your oral health and confidence. These are the conditions we correct most often.</p>
      </div>

      <div class="ig-conds">
        <div class="ig-cond">
          <div class="ig-cond__icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 9h16M6 9v3a6 6 0 0 0 12 0V9"/><path d="M8 15h8"/></svg></div>
          <h3>Overbite</h3>
          <p>When the top teeth extend too far over the lower teeth.</p>
        </div>
        <div class="ig-cond">
          <div class="ig-cond__icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 7v10M9.5 6v12M14.5 6v12M19 7v10"/></svg></div>
          <h3>Crowding</h3>
          <p>Overlapping teeth that are difficult to clean properly.</p>
        </div>
        <div class="ig-cond">
          <div class="ig-cond__icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6 6v12M18 6v12"/><path d="M9 12h6"/></svg></div>
          <h3>Gapped Teeth</h3>
          <p>Significant spacing between teeth that can affect the bite.</p>
        </div>
        <div class="ig-cond">
          <div class="ig-cond__icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 8l14 8M5 16l14-8"/></svg></div>
          <h3>Crossbite</h3>
          <p>Also known as an underbite, where the jaws don't align.</p>
        </div>
        <div class="ig-cond">
          <div class="ig-cond__icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 8h16M4 16h16"/></svg></div>
          <h3>Open Bite</h3>
          <p>When the top and bottom teeth don't meet on closing.</p>
        </div>
      </div>

      <div class="ig-btns ig-btns--c" style="margin-top:clamp(28px,3.2vw,44px);">
        <a class="ig-btn ig-btn--primary" href="#ig-consult">Book A No-Cost Consultation</a>
        <a class="ig-btn ig-btn--out" href="tel:<?= e($loc['tel']) ?>">Call Now</a>
      </div>
    </div>
  </section>


  <!-- ==========================================================
       16. FINAL CTA
       ========================================================== -->
  <section class="ig-sec ig-cta ig-cta--split">
    <div class="ig-wrap">
      <div class="ig-cta__grid">
        <div>
          <span class="ig-kicker">We Can't Wait To See You Soon!</span>
          <h2>Your Trusted Orthodontists in <em><?= e($loc['name']) ?></em> Are Ready to Help</h2>
          <p>Our <?= e($loc['name']) ?> team believes in welcoming every patient with the highest standard of orthodontic care — from your first consultation to the day your braces come off.</p>
          <div class="ig-btns">
            <a class="ig-btn ig-btn--primary" href="#ig-consult">Schedule Now</a>
            <a class="ig-btn ig-btn--white" href="tel:<?= e($loc['tel']) ?>">Call <?= e($loc['phone']) ?></a>
          </div>
        </div>
        <div class="ig-cta__img">
          <!-- EDIT: team photo for this office -->
          <img src="/assets/img/happy-family.jpg"
               alt="The Ignite Orthodontics <?= e($loc['name']) ?> team" width="826" height="591" loading="lazy" decoding="async">
        </div>
      </div>
    </div>
  </section>


    <!-- ==========================================================
       18. FAQ
       ========================================================== -->
  <section class="ig-sec ig-sec--tint">
    <div class="ig-wrap">
      <div class="ig-head">
        <span class="ig-kicker">Still Have Questions?</span>
        <h2 class="ig-h2">Frequently Asked <em>Questions</em></h2>
      </div>

      <div class="ig-faq">
        <div class="ig-faq__tabs" id="igFaqTabs">
          <button class="ig-faq__tab is-active" type="button" data-cat="all">All</button>
          <button class="ig-faq__tab" type="button" data-cat="general">General</button>
          <button class="ig-faq__tab" type="button" data-cat="condition">Conditions</button>
          <button class="ig-faq__tab" type="button" data-cat="age">Age</button>
          <button class="ig-faq__tab" type="button" data-cat="insurance">Insurance</button>
          <button class="ig-faq__tab" type="button" data-cat="treatment">Treatment</button>
        </div>

        <!-- EDIT: swap in Ignite's own answers -->
        <div id="igFaqList">
          <div class="ig-q" data-cat="general">
            <button class="ig-q__btn" type="button" aria-expanded="false">
              How do I schedule an appointment at Ignite Orthodontics in <?= e($loc['name']) ?>?
              <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 15.5 4.5 8l1.6-1.6L12 12.3l5.9-5.9L19.5 8z"/></svg>
            </button>
            <div class="ig-q__a"><p>Call our <?= e($loc['name']) ?> office on <?= e($loc['phone']) ?> or complete the no-cost consultation form on this page. We'll confirm your appointment and send everything you need beforehand.</p></div>
          </div>

          <div class="ig-q" data-cat="general">
            <button class="ig-q__btn" type="button" aria-expanded="false">
              What kind of follow-up care is available?
              <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 15.5 4.5 8l1.6-1.6L12 12.3l5.9-5.9L19.5 8z"/></svg>
            </button>
            <div class="ig-q__a"><p>Regular adjustment visits are built into every treatment plan, and retainers are fitted once active treatment ends. If something breaks between visits, call us and we'll get you seen.</p></div>
          </div>

          <div class="ig-q" data-cat="insurance">
            <button class="ig-q__btn" type="button" aria-expanded="false">
              Does Ignite Orthodontics in <?= e($loc['name']) ?> offer flexible payment options?
              <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 15.5 4.5 8l1.6-1.6L12 12.3l5.9-5.9L19.5 8z"/></svg>
            </button>
            <div class="ig-q__a"><p>Yes. We offer interest-free in-house payment plans with no hidden fees, and we accept most major insurance plans. We'll verify your benefits before treatment starts.</p></div>
          </div>

          <div class="ig-q" data-cat="condition">
            <button class="ig-q__btn" type="button" aria-expanded="false">
              Can an orthodontist fix a bad bite?
              <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 15.5 4.5 8l1.6-1.6L12 12.3l5.9-5.9L19.5 8z"/></svg>
            </button>
            <div class="ig-q__a"><p>Yes. Overbite, underbite, crossbite and open bite are all correctable. Which approach we recommend depends on your age and how the jaws are positioned, which we'll assess at your consultation.</p></div>
          </div>

          <div class="ig-q" data-cat="age">
            <button class="ig-q__btn" type="button" aria-expanded="false">
              Is there an age limit for orthodontic treatment?
              <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 15.5 4.5 8l1.6-1.6L12 12.3l5.9-5.9L19.5 8z"/></svg>
            </button>
            <div class="ig-q__a"><p>No. Healthy teeth can be moved at any age. We treat children from around seven through to adults in their sixties and beyond.</p></div>
          </div>

          <div class="ig-q" data-cat="treatment">
            <button class="ig-q__btn" type="button" aria-expanded="false">
              How long does braces treatment usually last?
              <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 15.5 4.5 8l1.6-1.6L12 12.3l5.9-5.9L19.5 8z"/></svg>
            </button>
            <div class="ig-q__a"><p>Most cases run between 12 and 24 months. Your orthodontist will give you a specific estimate at your consultation, once they've seen your x-rays and scans.</p></div>
          </div>

          <div class="ig-q" data-cat="treatment">
            <button class="ig-q__btn" type="button" aria-expanded="false">
              What is the cost of adult braces in <?= e($loc['name']) ?>?
              <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 15.5 4.5 8l1.6-1.6L12 12.3l5.9-5.9L19.5 8z"/></svg>
            </button>
            <div class="ig-q__a"><p>Cost depends on the treatment type and how long you're in braces. We'll give you an exact figure — with the monthly payment broken out — at your no-cost consultation, before you commit to anything.</p></div>
          </div>
        </div>
      </div>
    </div>
  </section>

</div>
