<?php /* GENERATED by tools/extract.php from menu.html. Edit the source file and re-run; changes here are overwritten. */ ?>
<div class="ig-nav-root">

  <header class="ig-header" id="igHeader">
    <div class="ig-accent"></div>

    <div class="ig-bar">

      <!-- ============ LEFT: UTILITY LINKS (desktop) ============ -->
      <nav class="ig-util" aria-label="Contact and locations">

        <!-- EDIT: phone number -->
        <div class="ig-util__item">
          <a class="ig-util__link" href="tel:<?= e(cfg('phone_tel')) ?>">
            <svg width="17" height="17" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M6.6 10.8c1.4 2.8 3.8 5.1 6.6 6.6l2.2-2.2c.3-.3.7-.4 1-.2 1.2.4 2.4.6 3.6.6.6 0 1 .4 1 1V20c0 .6-.4 1-1 1-9.4 0-17-7.6-17-17 0-.6.4-1 1-1h3.5c.6 0 1 .4 1 1 0 1.3.2 2.5.6 3.6.1.3 0 .7-.2 1l-2.3 2.2z"/></svg>
            Call Us
          </a>
        </div>

        <!-- LOCATIONS DROPDOWN -->
        <div class="ig-util__item" data-ig-dropdown>
          <button class="ig-util__link" type="button" aria-expanded="false" aria-haspopup="true">
            <svg width="17" height="17" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 2C8.1 2 5 5.1 5 9c0 5.2 7 13 7 13s7-7.8 7-13c0-3.9-3.1-7-7-7zm0 9.5A2.5 2.5 0 1 1 12 6.5a2.5 2.5 0 0 1 0 5z"/></svg>
            Our Locations (<?= count(locations()) ?>)
            <svg class="ig-util__caret" width="12" height="12" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 15.5 4.5 8l1.6-1.6L12 12.3l5.9-5.9L19.5 8z"/></svg>
          </button>

          <!-- EDIT: real Ignite Orthodontics locations -->
          <div class="ig-drop" role="menu">
<?php foreach (locations() as $l): ?>
            <a href="/locations/<?= e($l['slug']) ?>/" role="menuitem">
              <b><?= e($l['name']) ?></b>
              <span><?= e($l['address_full']) ?></span>
            </a>
<?php endforeach; ?>
          </div>
        </div>
      </nav>

      <!-- ============ CENTER: LOGO ============ -->
      <a class="ig-logo" href="/" aria-label="Ignite Orthodontics — home">
        <img src="/assets/img/ignitelogo.png"
             alt="Ignite Orthodontics" width="300" height="52">
      </a>

      <!-- ============ RIGHT: CTAs + HAMBURGER ============ -->
      <div class="ig-right">

        <!-- mobile-only quick call — EDIT: phone number -->
        <a class="ig-mob-call" href="tel:<?= e(cfg('phone_tel')) ?>" aria-label="Call Ignite Orthodontics">
          <svg width="19" height="19" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M6.6 10.8c1.4 2.8 3.8 5.1 6.6 6.6l2.2-2.2c.3-.3.7-.4 1-.2 1.2.4 2.4.6 3.6.6.6 0 1 .4 1 1V20c0 .6-.4 1-1 1-9.4 0-17-7.6-17-17 0-.6.4-1 1-1h3.5c.6 0 1 .4 1 1 0 1.3.2 2.5.6 3.6.1.3 0 .7-.2 1l-2.3 2.2z"/></svg>
        </a>

        <div class="ig-cta-group">
          <a class="ig-btn ig-btn--consult" href="<?= e(booking_url()) ?>">Request a Consultation</a>
        </div>

        <!-- inline styles are deliberate: they beat any theme stylesheet rule,
             so the three bars stay white and sized even on a hostile theme -->
        <button class="ig-burger" id="igBurger" type="button"
                aria-label="Open menu" aria-expanded="false" aria-controls="igPanel">
          <span style="display:block;width:32px;height:3px;border-radius:3px;background:#FFFFFF"></span>
          <span style="display:block;width:32px;height:3px;border-radius:3px;background:#FFFFFF"></span>
          <span style="display:block;width:32px;height:3px;border-radius:3px;background:#FFFFFF"></span>
        </button>
      </div>
    </div>
  </header>

  <!-- ============ OFF-CANVAS PANEL ============ -->
  <div class="ig-scrim" id="igScrim" hidden></div>

  <aside class="ig-panel" id="igPanel" aria-label="Main menu" aria-hidden="true">

    <div class="ig-panel__head">
      <a href="/" aria-label="Ignite Orthodontics — home">
        <img src="/assets/img/ignitelogo.png"
             alt="Ignite Orthodontics" width="240" height="42">
      </a>
      <button class="ig-close" id="igClose" type="button" aria-label="Close menu">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M19 6.4 17.6 5 12 10.6 6.4 5 5 6.4 10.6 12 5 17.6 6.4 19 12 13.4 17.6 19 19 17.6 13.4 12z"/></svg>
      </button>
    </div>

    <div class="ig-panel__body">

      <ul class="ig-menu">

        <li>
          <div class="ig-menu__row">
            <a class="ig-menu__link" href="/about-us/">About Us</a>
          </div>
        </li>

        <li data-ig-parent>
          <div class="ig-menu__row">
            <a class="ig-menu__link" href="/treatments/">Our Treatments</a>
            <button class="ig-menu__toggle" type="button" aria-label="Toggle Our Treatments submenu" aria-expanded="false">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 15.5 4.5 8l1.6-1.6L12 12.3l5.9-5.9L19.5 8z"/></svg>
            </button>
          </div>
          <div class="ig-sub">
<?php foreach (service_menu() as [$href, $label]): ?>
            <a href="<?= e($href) ?>"><?= e($label) ?></a>
<?php endforeach; ?>
</div>
        </li>

        <li>
          <div class="ig-menu__row">
            <a class="ig-menu__link" href="/patient-info/">Patient Info</a>
          </div>
        </li>

        <li data-ig-parent>
          <div class="ig-menu__row">
            <a class="ig-menu__link" href="/locations/">Our Locations</a>
            <button class="ig-menu__toggle" type="button" aria-label="Toggle Our Locations submenu" aria-expanded="false">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 15.5 4.5 8l1.6-1.6L12 12.3l5.9-5.9L19.5 8z"/></svg>
            </button>
          </div>
          <div class="ig-sub">
<?php foreach (locations() as $l): ?>
            <a href="/locations/<?= e($l['slug']) ?>/"><?= e($l['name']) ?></a>
<?php endforeach; ?>
</div>
        </li>

        <li>
          <div class="ig-menu__row">
            <a class="ig-menu__link" href="/blog/">Blog</a>
          </div>
        </li>

        <li>
          <div class="ig-menu__row">
            <a class="ig-menu__link" href="/refer-a-patient/">Refer a Patient</a>
          </div>
        </li>

      </ul>

      <div class="ig-panel__contact">
        <h6>Get in touch</h6>
        <a href="tel:<?= e(cfg('phone_tel')) ?>"><!-- EDIT -->
          <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M6.6 10.8c1.4 2.8 3.8 5.1 6.6 6.6l2.2-2.2c.3-.3.7-.4 1-.2 1.2.4 2.4.6 3.6.6.6 0 1 .4 1 1V20c0 .6-.4 1-1 1-9.4 0-17-7.6-17-17 0-.6.4-1 1-1h3.5c.6 0 1 .4 1 1 0 1.3.2 2.5.6 3.6.1.3 0 .7-.2 1l-2.3 2.2z"/></svg>
          <?= e(cfg('phone')) ?>
        </a>
        <a href="mailto:sterlingheights@igniteorthodontics.com"><!-- EDIT -->
          <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M20 4H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2zm0 4.2-8 4.8-8-4.8V6l8 4.8L20 6v2.2z"/></svg>
          sterlingheights@igniteorthodontics.com
        </a>
      </div>
    </div>

    <div class="ig-panel__foot">
      <a class="ig-btn ig-btn--consult" href="<?= e(booking_url()) ?>">Request a Consultation</a>
    </div>
  </aside>

  <!-- keeps page content from sliding under the fixed header -->
  <div class="ig-spacer" id="igSpacer"></div>
</div>
