<?php
/**
 * Rebuilds the generated assets and views in public/ from the design source files
 * in the repo root (menu.html, home-preview.html, location-preview.html,
 * kids-braces-page-layout.html).
 *
 *   php tools/extract.php
 *
 * Re-run after editing any of those source files. Every replacement is checked:
 * if a source file changes so a replacement no longer matches, the script stops
 * instead of silently producing a broken page.
 */
declare(strict_types=1);

$root = dirname(__DIR__);
$pub  = $root . '/public';

const VIEW_HEADER = "<?php /* GENERATED by tools/extract.php from %s. Edit the source file and re-run; changes here are overwritten. */ ?>\n";

function src(string $file): string
{
    global $root;
    $s = file_get_contents("$root/$file");
    if ($s === false) throw new RuntimeException("missing $file");
    return str_replace("\r\n", "\n", $s);
}

/** Text between $open and the next $close (first or last $open in the file). */
function block(string $s, string $open, string $close, bool $last = false): string
{
    $a = $last ? strrpos($s, $open) : strpos($s, $open);
    if ($a === false) throw new RuntimeException("no $open");
    $a += strlen($open);
    $b = strpos($s, $close, $a);
    if ($b === false) throw new RuntimeException("no $close");
    return trim(substr($s, $a, $b - $a)) . "\n";
}

/** From the first $start (inclusive) to the last $end (exclusive). */
function between(string $s, string $start, string $end): string
{
    $a = strpos($s, $start);
    $b = strrpos($s, $end);
    if ($a === false || $b === false || $b < $a) throw new RuntimeException("between: $start");
    return rtrim(substr($s, $a, $b - $a)) . "\n";
}

function localize(string $s): string
{
    return preg_replace(
        '#https://deepskyblue-okapi-345023\.hostingersite\.com/wp-content/uploads/\d{4}/\d{2}/([^"\'\s)]+)#',
        '/assets/img/$1',
        $s
    );
}

function rep(string $s, string $from, string $to): string
{
    $s = str_replace($from, $to, $s, $n);
    if ($n === 0) throw new RuntimeException("no match for: $from");
    return $s;
}

/** Regex replace with a literal replacement (no backreference parsing). */
function rep_re(string $s, string $re, string $to): string
{
    $s = preg_replace_callback($re, static fn() => $to, $s, -1, $n);
    if (!$n) throw new RuntimeException("no match for regex: $re");
    return $s;
}

/** Regex replace keeping capture groups 1 and 2 around $inner. */
function wrap_re(string $s, string $re, string $inner): string
{
    $s = preg_replace_callback($re, static fn($m) => $m[1] . $inner . $m[2], $s, -1, $n);
    if (!$n) throw new RuntimeException("no match for regex: $re");
    return $s;
}

function put(string $path, string $data): void
{
    global $pub;
    $f = "$pub/$path";
    if (!is_dir(dirname($f))) mkdir(dirname($f), 0777, true);
    file_put_contents($f, $data);
    printf("wrote %-36s %7d bytes\n", $path, strlen($data));
}

function brand_phone(string $s): string
{
    $s = rep($s, 'tel:+15863937972', "tel:<?= e(cfg('phone_tel')) ?>");
    return rep($s, '(586) 393-7972', "<?= e(cfg('phone')) ?>");
}

/* ------------------------------------------------------------------ header */
$m = src('menu.html');
put('assets/css/header.css', "/* generated from menu.html */\n" . block($m, '<style>', '</style>'));
put('assets/js/header.js', "/* generated from menu.html */\n" . block($m, '<script>', '</script>'));

$h = localize(between($m, '<div class="ig-nav-root">', '<script>'));
$h = rep_re($h, '#<div class="ig-drop" role="menu">.*?</div>#s', <<<'HTML'
<div class="ig-drop" role="menu">
<?php foreach (locations() as $l): ?>
            <a href="/locations/<?= e($l['slug']) ?>/" role="menuitem">
              <b><?= e($l['name']) ?></b>
              <span><?= e($l['address_full']) ?></span>
            </a>
<?php endforeach; ?>
          </div>
HTML);
$h = wrap_re($h, '#(<a class="ig-menu__link" href="/locations/">Our Locations</a>.*?<div class="ig-sub">).*?(</div>)#s', <<<'HTML'

<?php foreach (locations() as $l): ?>
            <a href="/locations/<?= e($l['slug']) ?>/"><?= e($l['name']) ?></a>
<?php endforeach; ?>

HTML);
$h = rep($h, 'Our Locations (6)', 'Our Locations (<?= count(locations()) ?>)');
$h = brand_phone($h);
// no "Contact Us" item in the menu (desktop bar or mobile panel)
$h = rep_re($h, '#\s*<!-- EDIT: email address -->\s*<div class="ig-util__item ig-util__item--contact">.*?</div>#s', '');
$h = rep_re($h, '#\s*<li>\s*<div class="ig-menu__row">\s*<a class="ig-menu__link" href="/contact-us/">Contact Us</a>\s*</div>\s*</li>#s', '');
// "Request a Consultation" opens the booking popup (contact page is the no-JS fallback)
$h = rep($h, '<a class="ig-btn ig-btn--consult" href="/contact-us/">', '<a class="ig-btn ig-btn--consult" href="/contact-us/" data-book>');
put('app/views/partials/header.php', sprintf(VIEW_HEADER, 'menu.html') . $h);

/* -------------------------------------------------------------------- home */
$s = src('home-preview.html');
put('assets/css/home.css', "/* generated from home-preview.html */\n" . localize(block($s, '<style>', '</style>', true)));
// the finder has no map, so the search hint must not send people to one
$js = rep(block($s, '<script>', '</script>', true),
    "'No offices matched — press Search Nearest to look it up on the map.'",
    "'No offices matched. Try a city name or zip code.'");
put('assets/js/home.js', "/* generated from home-preview.html */\n" . $js);

$b = localize(between($s, '<div class="ig-home">', '<script>'));
// consultation form section -> shared call-to-action band
$b = rep_re($b, '#<section class="ig-form-sec" id="ig-consult">.*?</section>#s',
    "<?php require APP . '/views/partials/consult-cta.php'; ?>");
// the office list is data-driven so the CMS can manage it
$b = rep_re($b, '#<!-- =+\s*8\. FIND IGNITE.*?(?=<!-- =+\s*9\. FINAL CTA)#s',
    "<?php require APP . '/views/partials/finder.php'; ?>\n\n\n  ");
$b = brand_phone($b);
// phones hide the <br> in card titles ("Traditional<br>Metal"); keep a real space so words don't merge
$b = preg_replace('#(class="ig-card-t__title">[^<]*)<br>#', '$1 <br>', $b, -1, $n);
if (!$n) throw new RuntimeException('no card titles found');
put('app/views/home.php', sprintf(VIEW_HEADER, 'home-preview.html') . $b);

/* ---------------------------------------------------------------- location */
$s = src('location-preview.html');
put('assets/css/location.css', "/* generated from location-preview.html */\n" . localize(block($s, '<style>', '</style>', true)));
put('assets/js/location.js', "/* generated from location-preview.html */\n" . block($s, '<script>', '</script>', true));

$b = localize(between($s, '<div class="ig-locpage">', '<script>'));
// placeholder doctors and reviews must not go live
$b = rep_re($b, '#<!-- =+\s*5\. MEET YOUR ORTHODONTIST.*?(?=<!-- =+\s*6\. FAMILY)#s', '');
$b = rep_re($b, '#<!-- =+\s*10\. REVIEWS.*?(?=<!-- =+\s*14\. CONTACT)#s', '');
$b = rep_re($b, '#<table class="ig-hours">.*?</table>#s',
    '<p class="ig-lead" style="margin-top:18px;">Call the office for current hours and appointment availability.</p>');
$b = rep($b, '<br><b>24/7 emergency:</b> <a href="tel:+13135550100">(313) 555-0100</a>', '');
// offers must match the pricing on the home page hero
$b = rep($b, 'Braces for<br>$199<sup>*</sup>/Month', 'Braces from<br>$99<sup>*</sup>/Month');
$b = rep($b, 'Braces for Just $199*/Month with No Down Payment', 'Braces from just $99* per month. Offer terms and eligibility apply.');
$b = rep($b, 'Clear Aligners with<br>only $500* Down', 'Clear Aligners from<br>$185<sup>*</sup>/Month');
$b = rep($b, 'Start Clear Aligners Today with a Low Down Payment of Just $500!', 'Clear aligners from $185* per month. Offer terms and eligibility apply.');
// consultation form section -> shared call-to-action band, with this office's photo and phone
$b = rep_re($b, '#<section class="ig-form-sec" id="ig-consult">.*?</section>#s',
    "<?php \$ctaImage = '/assets/img/invisalign-braces-scaled.jpg'; \$ctaPhone = \$loc['phone']; \$ctaTel = \$loc['tel'];"
    . " require APP . '/views/partials/consult-cta.php'; ?>");
// per-office tokens (order matters: full address before the bare city name)
// no Google map embed (it links off the site): a photo fills the map box instead
$b = rep_re($b, '#<iframe src="https://maps\.google\.com/maps\?q=1010[^"]*"[^>]*></iframe>#s',
    '<img src="/assets/img/02-image.webp" alt="Smiling patient at Ignite Orthodontics Arlington Heights" width="288" height="467" loading="lazy" decoding="async">');
// the address is plain text: no links off the site
$b = rep($b, '<a href="https://maps.google.com/?q=1010+S+Arlington+Heights+Rd" target="_blank" rel="noopener">1010 S Arlington Heights Rd, Arlington Heights, IL 60005</a>',
    '1010 S Arlington Heights Rd, Arlington Heights, IL 60005');
$b = rep($b, '1010 S Arlington Heights Rd, Arlington Heights, IL 60005', "<?= e(\$loc['address_full']) ?>");
$b = str_replace('Arlington Heights, IL', "<?= e(\$loc['city']) ?>, MI", $b); // only in the reviews heading, removed above
$b = rep($b, 'Arlington Heights', "<?= e(\$loc['name']) ?>");
$b = rep($b, '(313) 555-0100', "<?= e(\$loc['phone']) ?>");
$b = rep($b, '+13135550100', "<?= e(\$loc['tel']) ?>");
$b = rep($b, 'arlington@igniteortho.com', "<?= e(\$loc['email']) ?>");
if (preg_match('/Arlington|555-0100|igniteortho\.com|Doctor One|Reviewer/', $b, $left)) {
    throw new RuntimeException("placeholder left in location template: {$left[0]}");
}
put('app/views/location.php', sprintf(VIEW_HEADER, 'location-preview.html') . $b);

/* ------------------------------------------------------------ kids braces */
$s = src('kids-braces-page-layout.html');
// Ignite brand palette and type in place of the copper / Outfit draft styling
$palette = [
    '#C76F34' => '#F47421', '#af5d28' => '#DA6210', '#061A3A' => '#0B2A55',
    '#0d2854' => '#082041', '#0d2d5e' => '#051A39',
    'rgba(199, 111, 52,' => 'rgba(244, 116, 33,', 'rgba(6, 26, 58,' => 'rgba(11, 42, 85,',
];
$css = str_ireplace(array_keys($palette), array_values($palette), block($s, '<style>', '</style>'));
// the draft styled bare body/h1/p globally; scope it so the header and footer are untouched
$css = rep($css, ':root {', '.kp {');
$css = rep($css, '*, *::before, *::after {', '.kp *, .kp *::before, .kp *::after {');
$css = rep($css, "body {\n            font-family", ".kp {\n            font-family");
$css = rep($css, 'h1, h2, h3, h4, h5 {', '.kp h1, .kp h2, .kp h3, .kp h4, .kp h5 {');
$css = rep($css, 'body { text-align: left; }', '.kp { text-align: left; }');
$css = rep($css, '.section-header h2, .section-header p, h1, h2, h3, h4, p { text-align: left !important; }',
    '.kp .section-header h2, .kp .section-header p, .kp h1, .kp h2, .kp h3, .kp h4, .kp p { text-align: left !important; }');
$css = rep($css, "'Outfit', sans-serif", '"Poppins", sans-serif');
$css = rep($css, "'DM Sans', sans-serif", '"Poppins", sans-serif');
put('assets/css/kids.css', "/* generated from kids-braces-page-layout.html */\n" . $css);

$js = block($s, '<script>', '</script>');
// the draft's location-picker popup is replaced by the site-wide booking popup
$js = rep_re($js, '#// Modal Handlers\s*\(function\(\) \{.*?\}\)\(\);#s', '');
put('assets/js/kids.js', "/* generated from kids-braces-page-layout.html */\n" . $js);

$b = substr(between($s, '<body>', '<!-- Scripts -->'), strlen('<body>'));
$b = localize(str_ireplace(array_keys($palette), array_values($palette), $b));
$b = rep($b, 'href="tel:8559163956"', "href=\"tel:<?= e(cfg('phone_tel')) ?>\"");
$b = rep($b, 'Call (855) 916-3956', "Call <?= e(cfg('phone')) ?>");
$b = rep($b, 'href="#" data-popup="true"', 'href="/contact-us/" data-book');
$b = rep_re($b, '#\s*<!-- =+\s*MODAL POPUP.*$#s', "\n");
if (preg_match('/Ignite Clinics|855|Lansing|data-popup|modal-overlay/', $b, $left)) {
    throw new RuntimeException("draft content left in kids page: {$left[0]}");
}
put('app/views/kids.php', sprintf(VIEW_HEADER, 'kids-braces-page-layout.html') . "<div class=\"kp\">\n" . $b . "</div>\n");

echo "done\n";
